@startuml carrinho
package Carrinho <<rectangle>> {

  ' Classes
  class Produtos {
    + id: Int
    + descProdutos: String
    preco: 
  }

  class Carrinhos {

  }

  ' Relacionamentos
  Produtos --o Carrinhos

}
@enduml