@startuml carrinho
package Carrinho <<rectangle>> {

  ' Classes
  class Produtos {
    + id: Int
    + descProdu
  }

  class Carrinhos {

  }

  ' Relacionamentos
  Produtos --o Carrinhos

}
@enduml