@startuml matriculaInformatica
skinparam ClassAttributeIconSize 0

package Modulo-matrícula/Informática <<Rectangle>> {

    class Aluno {
    - id: Int
    - nome: String
    - matrículas: Lista<Matrícula>
  }

  Aluno "1" -l-* "1..*" Matrícula: composição >

  class Matrícula {
    - id: Int
    - aluno: Aluno
    - tempo: Int
    - turma: Turma
    + registraMatrŕicula(): Int
  }

  Matrícula ..|> ControleNúmeroMatrícula: realização


  interface ControleNúmeroMatrícula <<interface>> {
    + registraMatrŕicula(): Int
  }

  ControleNúmeroMatrícula <.. Turma: dependência

  Matrícula "1..*" --* "1" Turma: composição >

  class Turma {
    - numero: Int
    - matrículas: Lista<Matrícula>
    - curso: Curso
    - quantidadeAluno: Int
    - turmaCompleta: B
    + getcontroleNúmeroMatrícula()
  }

  Turma "1..*"  -l-o "1" Curso: composição >
  Turma "1..*"  -l- "20..*" Aluno

  class Curso {
    - nome: String
    - profesor: String
    - turmas: List<Turma>
  }

}
@enduml