@startuml sisDeCobrança
  package Sistema_de_Cobranças <<rectangle>> {
    class cliente {
      - id: Int
      # nome: String
    }
    class cobrança {
      - id: Int
      # cliente
    }
    cliente "1" --o "0..*" cobrança
    class boleto {}
    cobrança "1" *-- "1" boleto
  }
@enduml