@startuml sisDeCobrança
  package Sistema_de_Cobranças <<rectangle>> {

    class Cliente {
      - id: Int
      # nome: String
      # cobranças: List<Cobrança>
      + fazerPagamento()
    }

    class Cobrança {
      - id: Int
      # cliente: Client
      # quitado: Boolean
      + gerarBoleto()
      + consultaBoleto(): Boolean
    }

    class Boleto {
      - id: Int
      # validade: Date
      # valor: Float
    }

    Cliente "1" --o "0..*" Cobrança
    Cobrança "1" *-- "1" Boleto

    interface Pagar  <<interface>> {
    }

    Cliente ..|> Pagar 

    interface GerarBoleto <<interface>> {
    }
  }
@enduml