@startuml sisDeCobrança
  package Sistema_de_Cobranças <<rectangle>> {
    class Cliente {
      - id: Int
      # nome: String
      # cobranças: List<Cobrança>
    }
    class Cobrança {
      - id: Int
      # cliente: Client
      
      
    }
    Cliente "1" --o "0..*" Cobrança
    class Boleto {
      - id: Int
      # valor: Double
      + gerarBoleto()
    }
    Cobrança "1" *-- "1" Boleto
  }
@enduml