@startuml sisDeCobrança
  package Sistema_de_Cobranças <<rectangle>> {
    class Cliente {
      - id: Int
      # nome: String
    }
    class obrança {
      - id: Int
      # cliente: 
    }
    Cliente "1" --o "0..*" cobrança
    class boleto {}
    cobrança "1" *-- "1" boleto
  }
@enduml